"""initial schema

Revision ID: 507921d67fb2
Revises: 
Create Date: 2026-10-04 00:34:36.938762
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '507921d67fb2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chain_transactions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('network', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('payload_summary', sa.JSON(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chain_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chain_transactions_case_id'), ['case_id'], unique=False)

    op.create_table('repository_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=240), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('default_branch', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_fork', sa.Boolean(), nullable=False),
    sa.Column('parent_full_name', sa.String(length=240), nullable=True),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('snapshot_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name', 'commit_sha', name='uq_snapshot_repo_commit')
    )
    with op.batch_alter_table('repository_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_snapshot_full_name', ['full_name'], unique=False)

    op.create_table('analysis_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=48), nullable=False),
    sa.Column('stage_states', sa.JSON(), nullable=False),
    sa.Column('origin_snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('target_snapshot_id', sa.String(length=64), nullable=False),
    sa.Column('origin_full_name', sa.String(length=240), nullable=False),
    sa.Column('target_full_name', sa.String(length=240), nullable=False),
    sa.Column('origin_commit', sa.String(length=64), nullable=False),
    sa.Column('target_commit', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['origin_snapshot_id'], ['repository_snapshots.id'], ),
    sa.ForeignKeyConstraint(['target_snapshot_id'], ['repository_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_jobs_status_created', ['status', 'created_at'], unique=False)

    op.create_table('cases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('origin_full_name', sa.String(length=240), nullable=False),
    sa.Column('target_full_name', sa.String(length=240), nullable=False),
    sa.Column('origin_commit', sa.String(length=64), nullable=False),
    sa.Column('target_commit', sa.String(length=64), nullable=False),
    sa.Column('manifest_hash', sa.String(length=80), nullable=False),
    sa.Column('current_revision', sa.Integer(), nullable=False),
    sa.Column('lifecycle', sa.String(length=32), nullable=False),
    sa.Column('submitter', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alternative_explanations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('support', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alternative_explanations', schema=None) as batch_op:
        batch_op.create_index('ix_alt_case_rev', ['case_id', 'revision_number'], unique=False)

    op.create_table('case_revisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('shared_upstream', sa.String(length=240), nullable=True),
    sa.Column('independent_origin_plausibility', sa.String(length=16), nullable=True),
    sa.Column('manifest_hash', sa.String(length=80), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('tx_hash', sa.String(length=80), nullable=True),
    sa.Column('network', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'revision_number', name='uq_case_revision')
    )
    with op.batch_alter_table('case_revisions', schema=None) as batch_op:
        batch_op.create_index('ix_revisions_case', ['case_id'], unique=False)

    op.create_table('challenges',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('base_revision', sa.Integer(), nullable=False),
    sa.Column('submitter', sa.String(length=128), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resulting_revision', sa.Integer(), nullable=True),
    sa.Column('tx_hash', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.create_index('ix_challenges_case', ['case_id'], unique=False)

    op.create_table('evidence_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('dna_layer', sa.String(length=24), nullable=False),
    sa.Column('evidence_type', sa.String(length=64), nullable=False),
    sa.Column('strength', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('origin_source', sa.JSON(), nullable=False),
    sa.Column('target_source', sa.JSON(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_items', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_case_rev', ['case_id', 'revision_number'], unique=False)
        batch_op.create_index('ix_evidence_layer', ['dna_layer'], unique=False)

    op.create_table('evidence_relations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('subject_kind', sa.String(length=32), nullable=False),
    sa.Column('subject_ref', sa.String(length=240), nullable=False),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.Column('object_kind', sa.String(length=32), nullable=False),
    sa.Column('object_ref', sa.String(length=240), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_relations', schema=None) as batch_op:
        batch_op.create_index('ix_relations_case', ['case_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence_relations', schema=None) as batch_op:
        batch_op.drop_index('ix_relations_case')

    op.drop_table('evidence_relations')
    with op.batch_alter_table('evidence_items', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_layer')
        batch_op.drop_index('ix_evidence_case_rev')

    op.drop_table('evidence_items')
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.drop_index('ix_challenges_case')

    op.drop_table('challenges')
    with op.batch_alter_table('case_revisions', schema=None) as batch_op:
        batch_op.drop_index('ix_revisions_case')

    op.drop_table('case_revisions')
    with op.batch_alter_table('alternative_explanations', schema=None) as batch_op:
        batch_op.drop_index('ix_alt_case_rev')

    op.drop_table('alternative_explanations')
    op.drop_table('cases')
    with op.batch_alter_table('analysis_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status_created')
        batch_op.drop_index(batch_op.f('ix_analysis_jobs_status'))

    op.drop_table('analysis_jobs')
    with op.batch_alter_table('repository_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshot_full_name')

    op.drop_table('repository_snapshots')
    with op.batch_alter_table('chain_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chain_transactions_case_id'))

    op.drop_table('chain_transactions')
    # ### end Alembic commands ###